// examples/react-app/src/App.tsx
import { useState, useEffect, useRef } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'

function App() {
  const [date, setDate] = useState<any>(null);
  const datepickerRef = useRef<any>(null);

  useEffect(() => {
    if (datepickerRef.current) {
      datepickerRef.current.addEventListener('dateSelect', (e: any) => {
        setDate(e.detail);
      });
    }
  }, []);

  return (
    <div style={{ padding: '2rem', fontFamily: 'sans-serif', maxWidth: '600px', margin: '0 auto', textAlign: 'center' }}>
      <div>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" style={{ width: '100px', display: 'block', margin: '0 auto 2rem' }} />
        </a>
      </div>
      <h1>React + ngxsmk-datepicker</h1>

      <div style={{ marginTop: '2rem' }}>
        <p>This is a React App rendering the Angular Web Component directly.</p>

        <div style={{ display: 'flex', justifyContent: 'center', marginTop: '2rem' }}>
          {/* Use the custom element natively */}
          <ngxsmk-datepicker
            ref={datepickerRef}
            mode="range"
            theme="light"
            style={{ width: '100%', maxWidth: '300px' }}
            classes={JSON.stringify({ header: 'bg-indigo-600 text-white rounded-t-lg' })}
          ></ngxsmk-datepicker>
        </div>

        <div style={{ marginTop: '2rem', padding: '1rem', background: '#f5f5f5', borderRadius: '8px', color: '#333' }}>
          <strong>Selected Date (In React State):</strong>
          <pre style={{ marginTop: '1rem' }}>
            {date ? JSON.stringify(date, null, 2) : 'No date selected'}
          </pre>
        </div>
      </div>
    </div>
  )
}

export default App

// examples/vue-app/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'

const date = ref(null)
const datepickerRef = ref<any>(null)

const handleDateSelect = (e: any) => {
  date.value = e.detail
}

onMounted(() => {
  if (datepickerRef.value) {
    datepickerRef.value.addEventListener('dateSelect', handleDateSelect)
  }
})
</script>

<template>
  <div class="container">
    <div>
      <a href="https://vuejs.org/" target="_blank">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>
    <h1>Vue + ngxsmk-datepicker</h1>

    <div class="content">
      <p>This is a Vue App rendering the Angular Web Component directly.</p>
      
      <div class="picker-wrapper">
        <!-- Use the custom element natively -->
        <ngxsmk-datepicker 
          ref="datepickerRef" 
          mode="range" 
          theme="light"
          :classes="JSON.stringify({ header: 'bg-green-600 text-white rounded-t-lg' })"
        ></ngxsmk-datepicker>
      </div>

      <div class="result">
        <strong>Selected Date (In Vue State):</strong>
        <pre>{{ date ? JSON.stringify(date, null, 2) : 'No date selected' }}</pre>
      </div>
    </div>
  </div>
</template>

<style scoped>
.container {
  padding: 2rem;
  font-family: sans-serif;
  max-width: 600px;
  margin: 0 auto;
  text-align: center;
}
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
.content {
  margin-top: 2rem;
}
.picker-wrapper {
  display: flex;
  justify-content: center;
  margin-top: 2rem;
}
ngxsmk-datepicker {
  width: 100%;
  max-width: 300px;
}
.result {
  margin-top: 2rem;
  padding: 1rem;
  background: #f5f5f5;
  border-radius: 8px;
  color: #333;
}
.result pre {
  margin-top: 1rem;
}
</style>
